import { LanguageCode } from '@vendure/common/lib/generated-types';
import { InitialData } from '@vendure/core';

export const initialData: InitialData = {
    defaultLanguage: LanguageCode.en,
    defaultZone: 'Americas',
    countries: [
    { code: 'AF', name: 'Afghanistan', zone: 'Asia' },
    { code: 'AX', name: 'Åland Islands', zone: 'Europe' },
    { code: 'AL', name: 'Albania', zone: 'Europe' },
    { code: 'DZ', name: 'Algeria', zone: 'Africa' },
    { code: 'AS', name: 'American Samoa', zone: 'Asia' },
    { code: 'AD', name: 'Andorra', zone: 'Europe' },
    { code: 'AO', name: 'Angola', zone: 'Africa' },
    { code: 'AI', name: 'Anguilla', zone: 'Americas' },
    { code: 'AG', name: 'Antigua and Barbuda', zone: 'Americas' },
    { code: 'AR', name: 'Argentina', zone: 'Americas' },
    { code: 'AM', name: 'Armenia', zone: 'Asia' },
    { code: 'AW', name: 'Aruba', zone: 'Americas' },
    { code: 'AU', name: 'Australia', zone: 'Asia' },
    { code: 'AT', name: 'Austria', zone: 'Europe' },
    { code: 'AZ', name: 'Azerbaijan', zone: 'Asia' },
    { code: 'BS', name: 'Bahamas', zone: 'Americas' },
    { code: 'BH', name: 'Bahrain', zone: 'Asia' },
    { code: 'BD', name: 'Bangladesh', zone: 'Asia' },
    { code: 'BB', name: 'Barbados', zone: 'Americas' },
    { code: 'BY', name: 'Belarus', zone: 'Europe' },
    { code: 'BE', name: 'Belgium', zone: 'Europe' },
    { code: 'BZ', name: 'Belize', zone: 'Americas' },
    { code: 'BJ', name: 'Benin', zone: 'Africa' },
    { code: 'BM', name: 'Bermuda', zone: 'Americas' },
    { code: 'BT', name: 'Bhutan', zone: 'Asia' },
    { code: 'BO', name: 'Bolivia (Plurinational State of)', zone: 'Americas' },
    { code: 'BQ', name: 'Bonaire, Sint Eustatius and Saba', zone: 'Americas' },
    { code: 'BA', name: 'Bosnia and Herzegovina', zone: 'Europe' },
    { code: 'BW', name: 'Botswana', zone: 'Africa' },
    { code: 'BV', name: 'Bouvet Island', zone: 'Americas' },
    { code: 'BR', name: 'Brazil', zone: 'Americas' },
    { code: 'IO', name: 'British Indian Ocean Territory', zone: 'Africa' },
    { code: 'BN', name: 'Brunei Darussalam', zone: 'Asia' },
    { code: 'BG', name: 'Bulgaria', zone: 'Europe' },
    { code: 'BF', name: 'Burkina Faso', zone: 'Africa' },
    { code: 'BI', name: 'Burundi', zone: 'Africa' },
    { code: 'CV', name: 'Cabo Verde', zone: 'Africa' },
    { code: 'KH', name: 'Cambodia', zone: 'Asia' },
    { code: 'CM', name: 'Cameroon', zone: 'Africa' },
    { code: 'CA', name: 'Canada', zone: 'Americas' },
    { code: 'KY', name: 'Cayman Islands', zone: 'Americas' },
    { code: 'CF', name: 'Central African Republic', zone: 'Africa' },
    { code: 'TD', name: 'Chad', zone: 'Africa' },
    { code: 'CL', name: 'Chile', zone: 'Americas' },
    { code: 'CN', name: 'China', zone: 'Asia' },
    { code: 'CX', name: 'Christmas Island', zone: 'Asia' },
    { code: 'CC', name: 'Cocos (Keeling) Islands', zone: 'Asia' },
    { code: 'CO', name: 'Colombia', zone: 'Americas' },
    { code: 'KM', name: 'Comoros', zone: 'Africa' },
    { code: 'CG', name: 'Congo', zone: 'Africa' },
    { code: 'CD', name: 'Congo (Democratic Republic of the)', zone: 'Africa' },
    { code: 'CK', name: 'Cook Islands', zone: 'Asia' },
    { code: 'CR', name: 'Costa Rica', zone: 'Americas' },
    { code: 'CI', name: 'Côte d\'Ivoire', zone: 'Africa' },
    { code: 'HR', name: 'Croatia', zone: 'Europe' },
    { code: 'CU', name: 'Cuba', zone: 'Americas' },
    { code: 'CW', name: 'Curaçao', zone: 'Americas' },
    { code: 'CY', name: 'Cyprus', zone: 'Asia' },
    { code: 'CZ', name: 'Czechia', zone: 'Europe' },
    { code: 'DK', name: 'Denmark', zone: 'Europe' },
    { code: 'DJ', name: 'Djibouti', zone: 'Africa' },
    { code: 'DM', name: 'Dominica', zone: 'Americas' },
    { code: 'DO', name: 'Dominican Republic', zone: 'Americas' },
    { code: 'EC', name: 'Ecuador', zone: 'Americas' },
    { code: 'EG', name: 'Egypt', zone: 'Africa' },
    { code: 'SV', name: 'El Salvador', zone: 'Americas' },
    { code: 'GQ', name: 'Equatorial Guinea', zone: 'Africa' },
    { code: 'ER', name: 'Eritrea', zone: 'Africa' },
    { code: 'EE', name: 'Estonia', zone: 'Europe' },
    { code: 'SZ', name: 'Eswatini', zone: 'Africa' },
    { code: 'ET', name: 'Ethiopia', zone: 'Africa' },
    { code: 'FK', name: 'Falkland Islands (Malvinas)', zone: 'Americas' },
    { code: 'FO', name: 'Faroe Islands', zone: 'Europe' },
    { code: 'FJ', name: 'Fiji', zone: 'Asia' },
    { code: 'FI', name: 'Finland', zone: 'Europe' },
    { code: 'FR', name: 'France', zone: 'Europe' },
    { code: 'GF', name: 'French Guiana', zone: 'Americas' },
    { code: 'PF', name: 'French Polynesia', zone: 'Asia' },
    { code: 'TF', name: 'French Southern Territories', zone: 'Africa' },
    { code: 'GA', name: 'Gabon', zone: 'Africa' },
    { code: 'GM', name: 'Gambia', zone: 'Africa' },
    { code: 'GE', name: 'Georgia', zone: 'Asia' },
    { code: 'DE', name: 'Germany', zone: 'Europe' },
    { code: 'GH', name: 'Ghana', zone: 'Africa' },
    { code: 'GI', name: 'Gibraltar', zone: 'Europe' },
    { code: 'GR', name: 'Greece', zone: 'Europe' },
    { code: 'GL', name: 'Greenland', zone: 'Americas' },
    { code: 'GD', name: 'Grenada', zone: 'Americas' },
    { code: 'GP', name: 'Guadeloupe', zone: 'Americas' },
    { code: 'GU', name: 'Guam', zone: 'Asia' },
    { code: 'GT', name: 'Guatemala', zone: 'Americas' },
    { code: 'GG', name: 'Guernsey', zone: 'Europe' },
    { code: 'GN', name: 'Guinea', zone: 'Africa' },
    { code: 'GW', name: 'Guinea-Bissau', zone: 'Africa' },
    { code: 'GY', name: 'Guyana', zone: 'Americas' },
    { code: 'HT', name: 'Haiti', zone: 'Americas' },
    { code: 'HM', name: 'Heard Island and McDonald Islands', zone: 'Asia' },
    { code: 'VA', name: 'Holy See', zone: 'Europe' },
    { code: 'HN', name: 'Honduras', zone: 'Americas' },
    { code: 'HK', name: 'Hong Kong', zone: 'Asia' },
    { code: 'HU', name: 'Hungary', zone: 'Europe' },
    { code: 'IS', name: 'Iceland', zone: 'Europe' },
    { code: 'IN', name: 'India', zone: 'Asia' },
    { code: 'ID', name: 'Indonesia', zone: 'Asia' },
    { code: 'IR', name: 'Iran (Islamic Republic of)', zone: 'Asia' },
    { code: 'IQ', name: 'Iraq', zone: 'Asia' },
    { code: 'IE', name: 'Ireland', zone: 'Europe' },
    { code: 'IM', name: 'Isle of Man', zone: 'Europe' },
    { code: 'IL', name: 'Israel', zone: 'Asia' },
    { code: 'IT', name: 'Italy', zone: 'Europe' },
    { code: 'JM', name: 'Jamaica', zone: 'Americas' },
    { code: 'JP', name: 'Japan', zone: 'Asia' },
    { code: 'JE', name: 'Jersey', zone: 'Europe' },
    { code: 'JO', name: 'Jordan', zone: 'Asia' },
    { code: 'KZ', name: 'Kazakhstan', zone: 'Asia' },
    { code: 'KE', name: 'Kenya', zone: 'Africa' },
    { code: 'KI', name: 'Kiribati', zone: 'Asia' },
    { code: 'KP', name: 'Korea (Democratic People\'s Republic of)', zone: 'Asia' },
    { code: 'KR', name: 'Korea (Republic of)', zone: 'Asia' },
    { code: 'KW', name: 'Kuwait', zone: 'Asia' },
    { code: 'KG', name: 'Kyrgyzstan', zone: 'Asia' },
    { code: 'LA', name: 'Lao People\'s Democratic Republic', zone: 'Asia' },
    { code: 'LV', name: 'Latvia', zone: 'Europe' },
    { code: 'LB', name: 'Lebanon', zone: 'Asia' },
    { code: 'LS', name: 'Lesotho', zone: 'Africa' },
    { code: 'LR', name: 'Liberia', zone: 'Africa' },
    { code: 'LY', name: 'Libya', zone: 'Africa' },
    { code: 'LI', name: 'Liechtenstein', zone: 'Europe' },
    { code: 'LT', name: 'Lithuania', zone: 'Europe' },
    { code: 'LU', name: 'Luxembourg', zone: 'Europe' },
    { code: 'MO', name: 'Macao', zone: 'Asia' },
    { code: 'MK', name: 'Macedonia (the former Yugoslav Republic of)', zone: 'Europe' },
    { code: 'MG', name: 'Madagascar', zone: 'Africa' },
    { code: 'MW', name: 'Malawi', zone: 'Africa' },
    { code: 'MY', name: 'Malaysia', zone: 'Asia' },
    { code: 'MV', name: 'Maldives', zone: 'Asia' },
    { code: 'ML', name: 'Mali', zone: 'Africa' },
    { code: 'MT', name: 'Malta', zone: 'Europe' },
    { code: 'MH', name: 'Marshall Islands', zone: 'Asia' },
    { code: 'MQ', name: 'Martinique', zone: 'Americas' },
    { code: 'MR', name: 'Mauritania', zone: 'Africa' },
    { code: 'MU', name: 'Mauritius', zone: 'Africa' },
    { code: 'YT', name: 'Mayotte', zone: 'Africa' },
    { code: 'MX', name: 'Mexico', zone: 'Americas' },
    { code: 'FM', name: 'Micronesia (Federated States of)', zone: 'Asia' },
    { code: 'MD', name: 'Moldova (Republic of)', zone: 'Europe' },
    { code: 'MC', name: 'Monaco', zone: 'Europe' },
    { code: 'MN', name: 'Mongolia', zone: 'Asia' },
    { code: 'ME', name: 'Montenegro', zone: 'Europe' },
    { code: 'MS', name: 'Montserrat', zone: 'Americas' },
    { code: 'MA', name: 'Morocco', zone: 'Africa' },
    { code: 'MZ', name: 'Mozambique', zone: 'Africa' },
    { code: 'MM', name: 'Myanmar', zone: 'Asia' },
    { code: 'NA', name: 'Namibia', zone: 'Africa' },
    { code: 'NR', name: 'Nauru', zone: 'Asia' },
    { code: 'NP', name: 'Nepal', zone: 'Asia' },
    { code: 'NL', name: 'Netherlands', zone: 'Europe' },
    { code: 'NC', name: 'New Caledonia', zone: 'Asia' },
    { code: 'NZ', name: 'New Zealand', zone: 'Asia' },
    { code: 'NI', name: 'Nicaragua', zone: 'Americas' },
    { code: 'NE', name: 'Niger', zone: 'Africa' },
    { code: 'NG', name: 'Nigeria', zone: 'Africa' },
    { code: 'NU', name: 'Niue', zone: 'Asia' },
    { code: 'NF', name: 'Norfolk Island', zone: 'Asia' },
    { code: 'MP', name: 'Northern Mariana Islands', zone: 'Asia' },
    { code: 'NO', name: 'Norway', zone: 'Europe' },
    { code: 'OM', name: 'Oman', zone: 'Asia' },
    { code: 'PK', name: 'Pakistan', zone: 'Asia' },
    { code: 'PW', name: 'Palau', zone: 'Asia' },
    { code: 'PS', name: 'Palestine, State of', zone: 'Asia' },
    { code: 'PA', name: 'Panama', zone: 'Americas' },
    { code: 'PG', name: 'Papua New Guinea', zone: 'Asia' },
    { code: 'PY', name: 'Paraguay', zone: 'Americas' },
    { code: 'PE', name: 'Peru', zone: 'Americas' },
    { code: 'PH', name: 'Philippines', zone: 'Asia' },
    { code: 'PN', name: 'Pitcairn', zone: 'Asia' },
    { code: 'PL', name: 'Poland', zone: 'Europe' },
    { code: 'PT', name: 'Portugal', zone: 'Europe' },
    { code: 'PR', name: 'Puerto Rico', zone: 'Americas' },
    { code: 'QA', name: 'Qatar', zone: 'Asia' },
    { code: 'RE', name: 'Réunion', zone: 'Africa' },
    { code: 'RO', name: 'Romania', zone: 'Europe' },
    { code: 'RU', name: 'Russian Federation', zone: 'Europe' },
    { code: 'RW', name: 'Rwanda', zone: 'Africa' },
    { code: 'BL', name: 'Saint Barthélemy', zone: 'Americas' },
    { code: 'SH', name: 'Saint Helena, Ascension and Tristan da Cunha', zone: 'Africa' },
    { code: 'KN', name: 'Saint Kitts and Nevis', zone: 'Americas' },
    { code: 'LC', name: 'Saint Lucia', zone: 'Americas' },
    { code: 'MF', name: 'Saint Martin (French part)', zone: 'Americas' },
    { code: 'PM', name: 'Saint Pierre and Miquelon', zone: 'Americas' },
    { code: 'VC', name: 'Saint Vincent and the Grenadines', zone: 'Americas' },
    { code: 'WS', name: 'Samoa', zone: 'Asia' },
    { code: 'SM', name: 'San Marino', zone: 'Europe' },
    { code: 'ST', name: 'Sao Tome and Principe', zone: 'Africa' },
    { code: 'SA', name: 'Saudi Arabia', zone: 'Asia' },
    { code: 'SN', name: 'Senegal', zone: 'Africa' },
    { code: 'RS', name: 'Serbia', zone: 'Europe' },
    { code: 'SC', name: 'Seychelles', zone: 'Africa' },
    { code: 'SL', name: 'Sierra Leone', zone: 'Africa' },
    { code: 'SG', name: 'Singapore', zone: 'Asia' },
    { code: 'SX', name: 'Sint Maarten (Dutch part)', zone: 'Americas' },
    { code: 'SK', name: 'Slovakia', zone: 'Europe' },
    { code: 'SI', name: 'Slovenia', zone: 'Europe' },
    { code: 'SB', name: 'Solomon Islands', zone: 'Asia' },
    { code: 'SO', name: 'Somalia', zone: 'Africa' },
    { code: 'ZA', name: 'South Africa', zone: 'Africa' },
    { code: 'GS', name: 'South Georgia and the South Sandwich Islands', zone: 'Americas' },
    { code: 'SS', name: 'South Sudan', zone: 'Africa' },
    { code: 'ES', name: 'Spain', zone: 'Europe' },
    { code: 'LK', name: 'Sri Lanka', zone: 'Asia' },
    { code: 'SD', name: 'Sudan', zone: 'Africa' },
    { code: 'SR', name: 'Suriname', zone: 'Americas' },
    { code: 'SJ', name: 'Svalbard and Jan Mayen', zone: 'Europe' },
    { code: 'SE', name: 'Sweden', zone: 'Europe' },
    { code: 'CH', name: 'Switzerland', zone: 'Europe' },
    { code: 'SY', name: 'Syrian Arab Republic', zone: 'Asia' },
    { code: 'TW', name: 'Taiwan, Province of China', zone: 'Asia' },
    { code: 'TJ', name: 'Tajikistan', zone: 'Asia' },
    { code: 'TZ', name: 'Tanzania, United Republic of', zone: 'Africa' },
    { code: 'TH', name: 'Thailand', zone: 'Asia' },
    { code: 'TL', name: 'Timor-Leste', zone: 'Asia' },
    { code: 'TG', name: 'Togo', zone: 'Africa' },
    { code: 'TK', name: 'Tokelau', zone: 'Asia' },
    { code: 'TO', name: 'Tonga', zone: 'Asia' },
    { code: 'TT', name: 'Trinidad and Tobago', zone: 'Americas' },
    { code: 'TN', name: 'Tunisia', zone: 'Africa' },
    { code: 'TR', name: 'Turkey', zone: 'Asia' },
    { code: 'TM', name: 'Turkmenistan', zone: 'Asia' },
    { code: 'TC', name: 'Turks and Caicos Islands', zone: 'Americas' },
    { code: 'TV', name: 'Tuvalu', zone: 'Asia' },
    { code: 'UG', name: 'Uganda', zone: 'Africa' },
    { code: 'UA', name: 'Ukraine', zone: 'Europe' },
    { code: 'AE', name: 'United Arab Emirates', zone: 'Asia' },
    { code: 'GB', name: 'United Kingdom of Great Britain and Northern Ireland', zone: 'Americas' },
    { code: 'US', name: 'United States of America', zone: 'Americas' },
    { code: 'UM', name: 'United States Minor Outlying Islands', zone: 'Asia' },
    { code: 'UY', name: 'Uruguay', zone: 'Americas' },
    { code: 'UZ', name: 'Uzbekistan', zone: 'Asia' },
    { code: 'VU', name: 'Vanuatu', zone: 'Asia' },
    { code: 'VE', name: 'Venezuela (Bolivarian Republic of)', zone: 'Americas' },
    { code: 'VN', name: 'Viet Nam', zone: 'Asia' },
    { code: 'VG', name: 'Virgin Islands (British)', zone: 'Americas' },
    { code: 'VI', name: 'Virgin Islands (U.S.)', zone: 'Americas' },
    { code: 'WF', name: 'Wallis and Futuna', zone: 'Asia' },
    { code: 'EH', name: 'Western Sahara', zone: 'Africa' },
    { code: 'YE', name: 'Yemen', zone: 'Asia' },
    { code: 'ZM', name: 'Zambia', zone: 'Africa' },
    { code: 'ZW', name: 'Zimbabwe', zone: 'Africa' },
    ],
    taxRates: [
        { name: 'Standard Tax', percentage: 20 },
        { name: 'Reduced Tax', percentage: 10 },
        { name: 'Zero Tax', percentage: 0 },
    ],
    shippingMethods: [
        { name: 'Standard Shipping', price: 500 },
        { name: 'Express Shipping', price: 1500 },
    ],
    paymentMethods: [
        {
            name: 'Standard Payment',
            handler: {
                code: 'dummy-payment-handler',
                arguments: [{ name: 'automaticSettle', value: 'false' }],
            },
        },
    ],
    collections: [
        {
            name: 'Electronics',
            filters: [
                {
                    code: 'facet-value-filter',
                    args: { facetValueNames: ['Electronics'], containsAny: false },
                },
            ],
        },
        {
            name: 'Clothing',
            filters: [
                {
                    code: 'facet-value-filter',
                    args: { facetValueNames: ['Clothing'], containsAny: false },
                },
            ],
        },
    ],
};
